### ISSUE TITLE
(not really an issue) real life use examples of edcert

### ISSUE THREAD

**Issue by sa2ajj** [zombiemuffin/edcert#1]
I tried to find anything related to edcert however there seem to be no blog posts or anything else related to that.

I wonder how edcert is used.

**Comment by mboecker** [comment]
Hey there! Really glad you're interested in my crate. It was my first real project in rust, therefore it's not quite as professional (for example, that it's at 9.x, just because I went to 1.0 before reaching a stable API...).
As for your question:
I wrote this as part of a MMORPG server, to handle the handshake for encryption of the udp packets. As with most of these projects, it never got finished or even in a usable state. Therefore there are no examples of edcert in use. However, it has not much more features than stated in the readme. The basic workflow should be as follows, in the case edcert was designed for (client - server connections with udp)

1. create your "game master key"
2. create a cert for each of your gameservers, sign them with master key
3. save master public key to clients
4. let clients connect to game servers, check certs using master key

Therefore, the readme gives a pretty good overview. The corresponding code in reference to the points stated above are:

1. ```let (mpk, msk) = ed25519::generate_keypair();```
2. ```let mut cert = Certificate::generate_random(meta, expires); cert.sign_with_master(&msk);```
3. just store ```mpk``` in your gameclient basically
4. ```let cv = RootValidator::new(&mpk, NoRevoker); assert_eq!(true, cv.is_valid(&server_cert).is_ok());```

The only missing thing from the readme is basically certificate encoding. That is the embedding of the certificate in the handshake packet. The reason it's not in the readme itself, is because the default certificate encoding is handled, in a different crate, [edcert-compressor](https://github.com/zombiemuffin/edcert-compressor). Edcert was designed for the following handshake protocol:

- Client: *sending connection request, containing nonce or something and ephermeral public key*
- Server: *responding with signature of nonce and its own ephemeral public key (using its private key, which is signed by the certificate) and the certificate itself (including the certificate chain)
- Client: *checks certificate and signatures, if they are ok, the shared secret can be derived from its own private key and servers public key*
- Server: *derive shared secret*

I hope this clears up your question. I'm sorry for writing such a wall of text, but I'm kind of excited to see your response. You're the only person who ever seemed interested in this crate, and it's kind of sad. If you have any more questions, feel free to respond and I will try to do my best to answer them!

Regards

**Comment by sa2ajj** [comment]
Thank you very much for the expanded answer (the wall of text is highly appreciated 😄).

For your reference, I found this crate via https://ianix.com/pub/ed25519-deployment.html

(I'll close the issue since I got the answer I was looking for).
